from typing import Protocol
from uuid import UUID

from app.profile.domain.teacher import Teacher


class TeacherRepository(Protocol):
    def find_by_user_id(self, user_id: UUID) -> Teacher | None: ...
    def find_by_id(self, teacher_id: UUID) -> Teacher | None: ...
    def create(self, teacher: Teacher) -> Teacher: ...
    def update(self, teacher: Teacher) -> Teacher: ...
