from typing import Protocol
from uuid import UUID


class BlobStorage(Protocol):
    def upload_pdf(self, *, content: bytes, teacher_id: UUID, classroom_id: UUID, student_id: UUID, version: int) -> str: ...
    def download_url(self, *, blob_path: str) -> str: ...
    def template_url(self) -> str: ...
