from typing import Protocol
from uuid import UUID

from app.school.domain.classroom import Classroom


class ClassroomRepository(Protocol):
    def find_by_id(self, classroom_id: UUID) -> Classroom | None: ...
    def find_by_teacher_id(self, teacher_id: UUID) -> list[Classroom]: ...
    def find_by_name_and_teacher(self, name: str, teacher_id: UUID) -> Classroom | None: ...
    def create(self, classroom: Classroom) -> Classroom: ...
    def update(self, classroom: Classroom) -> Classroom: ...
    def delete(self, classroom_id: UUID) -> None: ...
