from typing import Protocol
from uuid import UUID

from app.school.domain.student import StudentConsent


class StudentConsentRepository(Protocol):
    def find_by_student_id(self, student_id: UUID) -> StudentConsent | None: ...
    def create(self, consent: StudentConsent) -> StudentConsent: ...
    def update(self, consent: StudentConsent) -> StudentConsent: ...
    def delete_by_student_id(self, student_id: UUID) -> None: ...
