from typing import Protocol
from uuid import UUID

from app.school.domain.homeroom_teacher import HomeroomTeacher


class HomeroomTeacherRepository(Protocol):
    def find_by_user_id(self, user_id: UUID) -> HomeroomTeacher | None: ...
    def find_by_id(self, teacher_id: UUID) -> HomeroomTeacher | None: ...
    def create(self, teacher: HomeroomTeacher) -> HomeroomTeacher: ...
    def update(self, teacher: HomeroomTeacher) -> HomeroomTeacher: ...
