from typing import Protocol
from uuid import UUID

from app.assessment.domain.template import AssessmentTemplate, AssessmentTemplateExercise
from app.assessment.domain.exercise import AssessmentExercise
from app.assessment.domain.question import OSQuestion, OSAnswer, MCQuestion, MCAnswerOption
from app.assessment.domain.prompt import PromptExercise, ExpectedAnswer
from app.assessment.domain.assessment import Assessment
from app.assessment.domain.attempt import AssessmentAttempt, ExerciseAttempt
from app.assessment.domain.response import MCResponse, OSResponse, SpeakingResponse, WritingResponse
from app.assessment.domain.metrics import SpeakingMetrics, WritingMetrics, AssessmentResult


class TemplateRepository(Protocol):
    def find_by_id(self, template_id: UUID) -> AssessmentTemplate | None: ...
    def find_by_teacher_id(self, teacher_id: UUID) -> list[AssessmentTemplate]: ...
    def create(self, template: AssessmentTemplate) -> AssessmentTemplate: ...
    def update(self, template: AssessmentTemplate) -> AssessmentTemplate: ...


class TemplateExerciseRepository(Protocol):
    def find_by_id(self, te_id: UUID) -> AssessmentTemplateExercise | None: ...
    def find_by_template_id(self, template_id: UUID) -> list[AssessmentTemplateExercise]: ...
    def create(self, te: AssessmentTemplateExercise) -> AssessmentTemplateExercise: ...
    def delete_by_template_id(self, template_id: UUID) -> None: ...


class ExerciseRepository(Protocol):
    def find_by_id(self, exercise_id: UUID) -> AssessmentExercise | None: ...
    def find_by_ids(self, ids: list[UUID]) -> list[AssessmentExercise]: ...
    def find_all(
        self,
        *,
        type_filter: str | None = None,
        difficulty_level: int | None = None,
        q: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[AssessmentExercise]: ...
    def create(self, exercise: AssessmentExercise) -> AssessmentExercise: ...


class OSQuestionRepository(Protocol):
    def find_by_exercise_id(self, exercise_id: UUID) -> OSQuestion | None: ...
    def create(self, q: OSQuestion) -> OSQuestion: ...


class OSAnswerRepository(Protocol):
    def find_by_question_id(self, question_id: UUID) -> OSAnswer | None: ...
    def create(self, a: OSAnswer) -> OSAnswer: ...


class MCQuestionRepository(Protocol):
    def find_by_exercise_id(self, exercise_id: UUID) -> MCQuestion | None: ...
    def create(self, q: MCQuestion) -> MCQuestion: ...
    def update(self, q: MCQuestion) -> MCQuestion: ...


class MCAnswerOptionRepository(Protocol):
    def find_by_question_id(self, question_id: UUID) -> list[MCAnswerOption]: ...
    def find_by_id(self, option_id: UUID) -> MCAnswerOption | None: ...
    def create(self, opt: MCAnswerOption) -> MCAnswerOption: ...
    def create_many(self, opts: list[MCAnswerOption]) -> list[MCAnswerOption]: ...


class PromptExerciseRepository(Protocol):
    def find_by_exercise_id(self, exercise_id: UUID) -> PromptExercise | None: ...
    def create(self, p: PromptExercise) -> PromptExercise: ...


class ExpectedAnswerRepository(Protocol):
    def find_by_prompt_exercise_id(self, prompt_exercise_id: UUID) -> ExpectedAnswer | None: ...
    def create(self, a: ExpectedAnswer) -> ExpectedAnswer: ...


class AssessmentRepository(Protocol):
    def find_by_id(self, assessment_id: UUID) -> Assessment | None: ...
    def find_by_teacher_id(self, teacher_id: UUID) -> list[Assessment]: ...
    def create(self, assessment: Assessment) -> Assessment: ...
    def update(self, assessment: Assessment) -> Assessment: ...


class AssessmentAttemptRepository(Protocol):
    def find_by_id(self, attempt_id: UUID) -> AssessmentAttempt | None: ...
    def find_by_assessment_id(self, assessment_id: UUID) -> list[AssessmentAttempt]: ...
    def create(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...
    def update(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...


class ExerciseAttemptRepository(Protocol):
    def find_by_id(self, ea_id: UUID) -> ExerciseAttempt | None: ...
    def find_by_assessment_attempt_id(self, attempt_id: UUID) -> list[ExerciseAttempt]: ...
    def create(self, ea: ExerciseAttempt) -> ExerciseAttempt: ...
    def create_many(self, eas: list[ExerciseAttempt]) -> list[ExerciseAttempt]: ...
    def update(self, ea: ExerciseAttempt) -> ExerciseAttempt: ...


class MCResponseRepository(Protocol):
    def find_by_exercise_attempt_id(self, ea_id: UUID) -> MCResponse | None: ...
    def create(self, r: MCResponse) -> MCResponse: ...
    def update(self, r: MCResponse) -> MCResponse: ...


class OSResponseRepository(Protocol):
    def find_by_exercise_attempt_id(self, ea_id: UUID) -> OSResponse | None: ...
    def create(self, r: OSResponse) -> OSResponse: ...
    def update(self, r: OSResponse) -> OSResponse: ...


class SpeakingResponseRepository(Protocol):
    def find_by_exercise_attempt_id(self, ea_id: UUID) -> SpeakingResponse | None: ...
    def create(self, r: SpeakingResponse) -> SpeakingResponse: ...
    def update(self, r: SpeakingResponse) -> SpeakingResponse: ...


class WritingResponseRepository(Protocol):
    def find_by_exercise_attempt_id(self, ea_id: UUID) -> WritingResponse | None: ...
    def create(self, r: WritingResponse) -> WritingResponse: ...
    def update(self, r: WritingResponse) -> WritingResponse: ...


class SpeakingMetricsRepository(Protocol):
    def create(self, m: SpeakingMetrics) -> SpeakingMetrics: ...
    def find_by_speaking_response_id(self, response_id: UUID) -> SpeakingMetrics | None: ...
    def update(self, m: SpeakingMetrics) -> SpeakingMetrics: ...


class WritingMetricsRepository(Protocol):
    def create(self, m: WritingMetrics) -> WritingMetrics: ...
    def find_by_writing_response_id(self, response_id: UUID) -> WritingMetrics | None: ...
    def update(self, m: WritingMetrics) -> WritingMetrics: ...


class AssessmentResultRepository(Protocol):
    def find_by_attempt_id(self, attempt_id: UUID) -> AssessmentResult | None: ...
    def create(self, r: AssessmentResult) -> AssessmentResult: ...
